have fun
Genesis-Front-End-School/clean-code-principes-37flwr pull request #2
Opened 2023-04-15 08:09 UTC by 37flwr

2023-04-16 06:41 UTC, xtadeushx commented on public/index.html
> +      content="Web site created using create-react-app"
додати свій опис

2023-04-16 06:42 UTC, xtadeushx commented on public/index.html
> +    <!--
видалити усі коментарі які не потрібні

2023-04-16 06:50 UTC, xtadeushx commented on src/components/Navbar/index.js
> +      <Link className="basic-navbar__link" to="/courses?page=1">
шлях  тегу **Link**  атрибуту **to** не захаркоджувати  а додавати через  зміну. Наприклад створити обєкт AppPaths = {
courses : '/courses'
} і вже додавати через обєкт

2023-04-16 06:50 UTC, xtadeushx commented on src/components/Navbar/index.js
> +      <Link className="basic-navbar__link" to="/account">
додавати шлях через властивість обєкту

2023-04-16 07:06 UTC, xtadeushx commented on src/components/Navbar/styles.scss
> +    color: white;
кольори додавати через змінні

2023-04-16 07:10 UTC, xtadeushx commented on src/context/PipProvider.js
> +      console.log(video.handleOnClose);
видалити не потрібний log

2023-04-16 07:12 UTC, xtadeushx commented on src/pages/Course/Lesson.js
> +        <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
додавати стилі через класи

2023-04-16 07:15 UTC, xtadeushx commented on src/pages/Course/index.js
> +    url: "https://api.wisey.app/api/v1/auth/anonymous?platform=subscriptions",
винести шлях у константу

2023-04-16 07:16 UTC, xtadeushx commented on src/pages/Course/index.js
> +    if (courseDetails && courses && !courses.find((c) => c.courseId === id)) {
винести логіку в окрему функціяю

2023-04-17 19:20 UTC, Diana064 approved these changes
Достатньо непогано структурований код, лише маленькі зауваження з якими згодна з попереднім ревювером

2023-04-17 19:20 UTC, Diana064 commented on src/index.js
Тут, я би зробила компонент, точніше використала, зі стайлу компонента компоннт 
темепройвайдер,
<img width="316" alt="Снимок экрана 2023-04-17 в 22 18 30" src="https://user-images.githubusercontent.com/98182589/232588890-2d980113-01cd-4449-84ec-456ad0dc2a65.png">
 обгорнула апп передала пропсом файлом с загальними стилями, і зміними, щоб потім стилізувати, було простіше, наприклад
 background-color: ${p => p.theme.colors.back};, так при зміні кольору бек, в тебе на всьому сайті змінюється колір. так можно зробити не тільки з кольором, 


 
 export const theme = {
  colors: {
    black: '#000',
    white: '#fff',
    subtitle: '#500805',
    title: '#000',
    border: '#A1D6E2',
    back: '#fff',
    backCourse: '#F1F1F2',
    mainText: '#896e69',
    peach: '#ffa577',
    text: '#313436',
  },
  space: [0, 2, 4, 8, 16, 32, 64, 128, 256],
  gap: [10, 15, 17, 20, 25, 30],

  fontSizes: {
    xs: '12px',
    s: '14px',
    m: '16px',
    l: '21px',
    xl: '32px',
  },
  fontWeights: {
    normal: 400,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
    big: '2px solid',
  },
  radii: {
    none: '0',
    sm: '4px',
    md: '8px',
    lg: '16px',
    round: '50%',
  },
};

2023-04-18 06:16 UTC, xtadeushx approved these changes

2023-04-19 13:26 UTC, olesmarola requested changes

2023-04-19 13:26 UTC, olesmarola commented on src/components/BasicPagination.js
> +  }
Wrap with useMemo

2023-04-19 13:26 UTC, olesmarola commented on src/components/Navbar/styles.scss
> +  padding-bottom: 15px !important;
Avoid using `!important`

2023-04-19 13:26 UTC, olesmarola commented on src/components/fallbacks/ErrorFallback/index.js
> +          <Button variant="outline-info" onClick={() => resetErrorBoundary()}>
```suggestion
          <Button variant="outline-info" onClick={resetErrorBoundary}>
```

2023-04-19 13:26 UTC, olesmarola commented on src/components/fallbacks/ErrorFallback/index.js
> +        <Button variant="outline-info" onClick={() => window.location.reload()}>
```suggestion
        <Button variant="outline-info" onClick={window.location.reload}>
```

2023-04-19 13:26 UTC, olesmarola commented on src/components/fallbacks/Loading/styles.scss
> +  height: calc(100vh - 70px);
Is 70px a header height? If yes, create a variable for that.

2023-04-19 13:26 UTC, olesmarola commented on src/context/PipProvider.js
> +      video.handleOnClose && video.handleOnClose(videoRef.current);
Use optional chaining:
```suggestion
      video.handleOnClose?.(videoRef.current);
```

2023-04-19 13:26 UTC, olesmarola commented on src/context/PipProvider.js
> +    newVideo?.link ? setVideo(newVideo) : setVideo(null);
```suggestion
    setVideo( newVideo?.link ? newVideo : null);
```

2023-04-19 13:26 UTC, olesmarola commented on src/pages/Course/Lesson.js
> +import classnames from "classnames";
```suggestion
import cn from "classnames";
```

2023-04-19 13:26 UTC, olesmarola commented on src/pages/Course/Lesson.js
> +      className={classnames(
```suggestion
      className={cn(
```

2023-04-19 13:26 UTC, olesmarola commented on src/pages/Course/Lesson.js
> +        onClick={() => status === "unlocked" && handleClick(id)}
Create function above

2023-04-19 13:26 UTC, olesmarola commented on src/pages/CourseList/CourseCard.js
> +      onMouseLeave={() => handleMouseOut((currState) => !currState)}
What does this function do?😨

2023-04-19 13:26 UTC, olesmarola commented on src/pages/CourseList/CourseCard.js
> +      onMouseOver={() => handleMouseOver((currState) => !currState)}
```suggestion
      onMouseOver={handleMouseOver}
```

2023-04-19 13:26 UTC, olesmarola commented on src/pages/CourseList/CourseCard.js
> +      onMouseLeave={() => handleMouseOut((currState) => !currState)}
```suggestion
      onMouseLeave={handleMouseOut}
```

2023-04-19 13:26 UTC, olesmarola commented on src/pages/CourseList/CourseCard.js
> +      ) : (
Double ternary... Double kill.😬

2023-04-19 13:26 UTC, olesmarola commented on package.json
> +    "@testing-library/user-event": "^13.5.0",
remove unused libs

2023-04-19 13:26 UTC, olesmarola commented on package.json
> +    "web-vitals": "^2.1.4"
remove unused

2023-04-27 11:40 UTC, merged